// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAdminUser = `-- name: CreateAdminUser :one
INSERT INTO admin_users (
    name,
    email,
    api_key
) VALUES (
    $1, $2, $3
)
RETURNING id, name, email, api_key, status, created_at
`

type CreateAdminUserParams struct {
	Name   string `json:"name"`
	Email  string `json:"email"`
	ApiKey string `json:"api_key"`
}

type CreateAdminUserRow struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Email     string             `json:"email"`
	ApiKey    string             `json:"api_key"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateAdminUser(ctx context.Context, arg CreateAdminUserParams) (CreateAdminUserRow, error) {
	row := q.db.QueryRow(ctx, createAdminUser, arg.Name, arg.Email, arg.ApiKey)
	var i CreateAdminUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.ApiKey,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getAdminByAPIKey = `-- name: GetAdminByAPIKey :one
SELECT 
    id,
    name,
    api_key,
    status
FROM admin_users
WHERE api_key = $1
LIMIT 1
`

type GetAdminByAPIKeyRow struct {
	ID     pgtype.UUID `json:"id"`
	Name   string      `json:"name"`
	ApiKey string      `json:"api_key"`
	Status string      `json:"status"`
}

func (q *Queries) GetAdminByAPIKey(ctx context.Context, apiKey string) (GetAdminByAPIKeyRow, error) {
	row := q.db.QueryRow(ctx, getAdminByAPIKey, apiKey)
	var i GetAdminByAPIKeyRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ApiKey,
		&i.Status,
	)
	return i, err
}

const updateAdminAPIKey = `-- name: UpdateAdminAPIKey :one
UPDATE admin_users
    SET
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, status, updated_at
`

type UpdateAdminAPIKeyRow struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Status    string             `json:"status"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateAdminAPIKey(ctx context.Context, id pgtype.UUID) (UpdateAdminAPIKeyRow, error) {
	row := q.db.QueryRow(ctx, updateAdminAPIKey, id)
	var i UpdateAdminAPIKeyRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAdminStatus = `-- name: UpdateAdminStatus :one
UPDATE admin_users
    SET status = $2,
    updated_at = NOW()
WHERE email = $1
RETURNING id, name, email, status, updated_at
`

type UpdateAdminStatusParams struct {
	Email  string `json:"email"`
	Status string `json:"status"`
}

type UpdateAdminStatusRow struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Email     string             `json:"email"`
	Status    string             `json:"status"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateAdminStatus(ctx context.Context, arg UpdateAdminStatusParams) (UpdateAdminStatusRow, error) {
	row := q.db.QueryRow(ctx, updateAdminStatus, arg.Email, arg.Status)
	var i UpdateAdminStatusRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Status,
		&i.UpdatedAt,
	)
	return i, err
}
