// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Tenant struct {
	ID                 pgtype.UUID        `json:"id"`
	Name               string             `json:"name"`
	ApiKey             string             `json:"api_key"`
	Tier               string             `json:"tier"`
	RateLimitReqPerMin int32              `json:"rate_limit_req_per_min"`
	Status             string             `json:"status"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}
