// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	CreateTenant(ctx context.Context, arg CreateTenantParams) (CreateTenantRow, error)
	GetTenantByAPIKey(ctx context.Context, apiKey string) (Tenant, error)
	UpdateTenantStatus(ctx context.Context, arg UpdateTenantStatusParams) (UpdateTenantStatusRow, error)
	UpdateTenantTierAndRate(ctx context.Context, arg UpdateTenantTierAndRateParams) (UpdateTenantTierAndRateRow, error)
}

var _ Querier = (*Queries)(nil)
