// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenants.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenants (
    name,
    api_key,
    tier,
    rate_limit_req_per_min,
    status
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, name, api_key, tier, rate_limit_req_per_min, status, created_at
`

type CreateTenantParams struct {
	Name               string `json:"name"`
	ApiKey             string `json:"api_key"`
	Tier               string `json:"tier"`
	RateLimitReqPerMin int32  `json:"rate_limit_req_per_min"`
	Status             string `json:"status"`
}

type CreateTenantRow struct {
	ID                 pgtype.UUID        `json:"id"`
	Name               string             `json:"name"`
	ApiKey             string             `json:"api_key"`
	Tier               string             `json:"tier"`
	RateLimitReqPerMin int32              `json:"rate_limit_req_per_min"`
	Status             string             `json:"status"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (CreateTenantRow, error) {
	row := q.db.QueryRow(ctx, createTenant,
		arg.Name,
		arg.ApiKey,
		arg.Tier,
		arg.RateLimitReqPerMin,
		arg.Status,
	)
	var i CreateTenantRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ApiKey,
		&i.Tier,
		&i.RateLimitReqPerMin,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getTenantByAPIKey = `-- name: GetTenantByAPIKey :one
SELECT 
    id,
    name,
    api_key,
    tier,
    rate_limit_req_per_min,
    status,
    created_at,
    updated_at
FROM tenants
WHERE api_key = $1
LIMIT 1
`

func (q *Queries) GetTenantByAPIKey(ctx context.Context, apiKey string) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantByAPIKey, apiKey)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ApiKey,
		&i.Tier,
		&i.RateLimitReqPerMin,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTenantStatus = `-- name: UpdateTenantStatus :one
UPDATE tenants
    SET status = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, status, updated_at
`

type UpdateTenantStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

type UpdateTenantStatusRow struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Status    string             `json:"status"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateTenantStatus(ctx context.Context, arg UpdateTenantStatusParams) (UpdateTenantStatusRow, error) {
	row := q.db.QueryRow(ctx, updateTenantStatus, arg.ID, arg.Status)
	var i UpdateTenantStatusRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTenantTierAndRate = `-- name: UpdateTenantTierAndRate :one
UPDATE tenants
SET 
    rate_limit_req_per_min = $2,
    tier = $3,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, api_key, tier, rate_limit_req_per_min, status, updated_at
`

type UpdateTenantTierAndRateParams struct {
	ID                 pgtype.UUID `json:"id"`
	RateLimitReqPerMin int32       `json:"rate_limit_req_per_min"`
	Tier               string      `json:"tier"`
}

type UpdateTenantTierAndRateRow struct {
	ID                 pgtype.UUID        `json:"id"`
	Name               string             `json:"name"`
	ApiKey             string             `json:"api_key"`
	Tier               string             `json:"tier"`
	RateLimitReqPerMin int32              `json:"rate_limit_req_per_min"`
	Status             string             `json:"status"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateTenantTierAndRate(ctx context.Context, arg UpdateTenantTierAndRateParams) (UpdateTenantTierAndRateRow, error) {
	row := q.db.QueryRow(ctx, updateTenantTierAndRate, arg.ID, arg.RateLimitReqPerMin, arg.Tier)
	var i UpdateTenantTierAndRateRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ApiKey,
		&i.Tier,
		&i.RateLimitReqPerMin,
		&i.Status,
		&i.UpdatedAt,
	)
	return i, err
}
